MVCLibraryApp/ViewModels/CreateBezoekerViewModel.cs
namespace MVCLibraryApp.ViewModels
{
    public class CreateBezoekerViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string Naam { get; set; }
        public int AbonnementID { get; set; }
    }
}

MVCLibraryApp/Controllers/MedewerkerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCLibraryApp.Models;
using MVCLibraryApp.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using MVCLibraryApp.Interfaces;
using MVCLibraryApp.Data;

namespace MVCLibraryApp.Controllers
{
    [Authorize(Roles = "Medewerker,Beheerder")]
    public class MedewerkerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BezoekerModel> _userManager;
        private readonly IUserRedirectionService _redirectionService;
        private readonly IGenerateInvoiceService _generateInvoiceService;


        public MedewerkerController(ApplicationDbContext context, UserManager<BezoekerModel> userManager, IUserRedirectionService redirectionService, IGenerateInvoiceService generateInvoiceService)
        {
            _context = context;
            _userManager = userManager;
            _redirectionService = redirectionService;
            _generateInvoiceService = generateInvoiceService;
        }


        public async Task<IActionResult> Dashboard()
        {
            var result = await _redirectionService.GetRedirectBasedOnRole(User);
            if (result != null)
                return result;

            return View();
        }

        public async Task<IActionResult> IndexBezoeker()
        {
            var users = await _userManager.GetUsersInRoleAsync("Bezoeker");
            var usersWithRoles = new List<(BezoekerModel, IList<string>)>();
            var userLockoutStatus = new Dictionary<string, bool>();

            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                usersWithRoles.Add((user, roles));
                var lockoutEndDate = await _userManager.GetLockoutEndDateAsync(user);
                userLockoutStatus.Add(user.Id, lockoutEndDate.HasValue && lockoutEndDate.Value > DateTimeOffset.Now);
            }

            // Eagerly load the Abonnement property for each user
            await _context.Bezoekers.Include(b => b.Abonnement).LoadAsync();

            ViewBag.Bezoekers = users;
            ViewBag.Rol = usersWithRoles.ToDictionary(x => x.Item1.Id, x => x.Item2);
            ViewBag.LockoutStatus = userLockoutStatus;

            return View(users);
        }



        public IActionResult CreateBezoeker()
        {
            try
            {
                // This should actually come from your database.
                var abonnementenList = _context.Abonnementen.ToList();
                ViewBag.Abonnementen = new SelectList(abonnementenList, "ID", "Type"); // Notice ID (not Id)
            }
            catch (Exception ex)
            {
                // Log or handle exception as needed
                Console.WriteLine(ex.Message);
            }

            return View(new CreateBezoekerViewModel());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateBezoeker(CreateBezoekerViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var abonnement = _context.Abonnementen.Find(model.AbonnementID);
                    if (abonnement != null)
                    {
                        var user = new BezoekerModel
                        {
                            UserName = model.Email,
                            Email = model.Email,
                            Naam = model.Naam,
                            AbonnementID = model.AbonnementID,
                        };

                        var result = await _userManager.CreateAsync(user, model.Password);
                        if (result.Succeeded)
                        {
                            await _userManager.AddToRoleAsync(user, "Bezoeker");
                            await _context.SaveChangesAsync();
                            return RedirectToAction(nameof(IndexBezoeker));
                        }
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Invalid Abonnement ID.");
                    }
                }
            }
            catch (Exception ex)
            {
                // Log or handle exception as needed
                Console.WriteLine(ex.Message);
            }

            // If we got this far, something failed, so redisplay form
            try
            {
                var abonnementenList = _context.Abonnementen.ToList();
                ViewBag.Abonnementen = new SelectList(abonnementenList, "ID", "Type");
            }
            catch (Exception ex)
            {
                // Log or handle exception as needed
                Console.WriteLine(ex.Message);
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditBezoeker(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var abonnementenList = _context.Abonnementen.ToList();
            ViewBag.Abonnementen = new SelectList(abonnementenList, "ID", "Type");

            var model = new BezoekerViewModel
            {
                Id = user.Id,
                Email = user.Email,
                Naam = user.Naam,
                AbonnementID = user.AbonnementID
            };

            Console.WriteLine("EditBezoeker - User found: " + user.Email); // Debugging statement
            Console.WriteLine("EditBezoeker - Abonnementen count: " + abonnementenList.Count); // Debugging statement

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBezoeker(BezoekerViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = await _userManager.FindByIdAsync(model.Id);
                    if (user == null)
                    {
                        return NotFound();
                    }

                    user.Email = model.Email;
                    user.Naam = model.Naam;
                    user.AbonnementID = model.AbonnementID;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(IndexBezoeker));
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                // Log or handle exception as needed
                Console.WriteLine(ex.Message);
            }

            // If we got this far, something failed, so redisplay form
            try
            {
                var abonnementenList = _context.Abonnementen.ToList();
                ViewBag.Abonnementen = new SelectList(abonnementenList, "ID", "Type");
            }
            catch (Exception ex)
            {
                // Log or handle exception as needed
                Console.WriteLine(ex.Message);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteBezoeker(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var result = await _userManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(IndexBezoeker));
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            // If we got this far, something failed, so redisplay form
            // Replace 'YourView' with the name of the view you want to display in case of an error
            return View("IndexBezoeker");
        }

        [HttpPost]
        public async Task<IActionResult> ToggleBlockUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user != null)
            {
                var lockoutEndDate = await _userManager.GetLockoutEndDateAsync(user);
                if (lockoutEndDate.HasValue && lockoutEndDate.Value > DateTimeOffset.Now)  // if user is blocked
                {
                    await _userManager.SetLockoutEndDateAsync(user, null);  // unblock the user
                }
                else
                {
                    await _userManager.SetLockoutEndDateAsync(user, DateTimeOffset.MaxValue);  // block the user
                }

                return RedirectToAction("IndexBezoeker");
            }

            return NotFound();
        }


        private FactuurModel CalculateFineAndGenerateInvoice(LeningModel lending, BezoekerModel user)
        {
            return _generateInvoiceService.CalculateFineAndGenerateInvoice(lending, user);
        }

MVCLibraryApp/Views/Medewerker/ConfirmPayment.cshtml
@model MVCLibraryApp.Models.FactuurModel
@{
    ViewData["Title"] = "ConfirmPayment";
}


<h1>Confirm Payment</h1>


<p>
    Amount to be paid: @Model.Amount
</p>

<form asp-controller="Medewerker" asp-action="ProcessPayment" method="post">
    <input type="hidden" name="id" value="@Model.Id" />  <!-- Use "id" as the name attribute -->
    <input type="submit" value="Pay" />
</form>

MVCLibraryApp/Views/Medewerker/CreateAbonnement.cshtml
@model MVCLibraryApp.Models.AbonnementModel

@{
    ViewData["Title"] = "CreateAbonnement";
}

<h1>Create</h1>

<h4>AbonnementModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateAbonnement">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaximaleItems" class="control-label"></label>
                <input asp-for="MaximaleItems" class="form-control" />
                <span asp-validation-for="MaximaleItems" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Uitleentermijn" class="control-label"></label>
                <input asp-for="Uitleentermijn" class="form-control" />
                <span asp-validation-for="Uitleentermijn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Verlengingen" class="control-label"></label>
                <input asp-for="Verlengingen" class="form-control" />
                <span asp-validation-for="Verlengingen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reserveringskosten" class="control-label"></label>
                <input asp-for="Reserveringskosten" class="form-control" />
                <span asp-validation-for="Reserveringskosten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Boetekosten" class="control-label"></label>
                <input asp-for="Boetekosten" class="form-control" />
                <span asp-validation-for="Boetekosten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Abonnementskosten" class="control-label"></label>
                <input asp-for="Abonnementskosten" class="form-control" />
                <span asp-validation-for="Abonnementskosten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="IndexAbonnement">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCLibraryApp/Views/Medewerker/CreateAuthor.cshtml
@model MVCLibraryApp.Models.AuteurModel

@{
    ViewData["Title"] = "CreateAuthor";
}

<h1>Create</h1>

<h4>AuteurModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateAuthor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="IndexAuthor">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCLibraryApp/Views/Medewerker/CreateBezoeker.cshtml
@model MVCLibraryApp.ViewModels.CreateBezoekerViewModel
@{
    ViewData["Title"] = "CreateBezoeker";
}

<h1>Create Bezoeker</h1>

<h4>BezoekerModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateBezoeker" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AbonnementID" class="control-label"></label>
                <select asp-for="AbonnementID" asp-items="ViewBag.Abonnementen" class="form-control"></select>
                <span asp-validation-for="AbonnementID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

            <!-- Display error messages -->
            @if (!ViewData.ModelState.IsValid)
            {
                <div class="alert alert-danger" role="alert">
                    <p>Please fix the following errors:</p>
                    <ul>
                        @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                        {
                            <li>@error.ErrorMessage</li>
                        }
                    </ul>
                </div>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="IndexBezoeker">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVCLibraryApp/Views/Medewerker/CreateItem.cshtml
@model MVCLibraryApp.Models.ItemModel

@{
    ViewData["Title"] = "CreateItem";
}

<h1>Create</h1>

<h4>ItemModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateItem">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titel" class="control-label"></label>
                <input asp-for="Titel" class="form-control" />
                <span asp-validation-for="Titel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuteurID" class="control-label"></label>
                <select asp-for="AuteurID" class ="form-control" asp-items="ViewBag.AuteurID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Publicatiejaar" class="control-label"></label>
                <input asp-for="Publicatiejaar" class="form-control" />
                <span asp-validation-for="Publicatiejaar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocatieID" class="control-label"></label>
                <select asp-for="LocatieID" class ="form-control" asp-items="ViewBag.LocatieID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="IndexItem">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCLibraryApp/Views/Medewerker/DeleteAbonnement.cshtml
@model MVCLibraryApp.Models.AbonnementModel

@{
    ViewData["Title"] = "DeleteAbonnement";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AbonnementModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaximaleItems)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaximaleItems)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Uitleentermijn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Uitleentermijn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Verlengingen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Verlengingen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reserveringskosten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reserveringskosten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Boetekosten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Boetekosten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Abonnementskosten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Abonnementskosten)
        </dd>
    </dl>
    
    <form asp-action="DeleteAbonnementConfirmed">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="IndexAbonnement">Back to List</a>
    </form>
</div>

MVCLibraryApp/Views/Medewerker/DetailsItem.cshtml
@model MVCLibraryApp.Models.ItemModel

@{
    ViewData["Title"] = "DetailsItem";
}

<h1>Details</h1>

<div>
    <h4>ItemModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Auteur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Auteur.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publicatiejaar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publicatiejaar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Locatie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Locatie.ID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="EditItem" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="IndexItem">Back to List</a>
</div>

MVCLibraryApp/Views/Medewerker/EditAbonnement.cshtml
@model MVCLibraryApp.Models.AbonnementModel

@{
    ViewData["Title"] = "EditAbonnement";
}

<h1>Edit</h1>

<h4>AbonnementModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditAbonnement">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaximaleItems" class="control-label"></label>
                <input asp-for="MaximaleItems" class="form-control" />
                <span asp-validation-for="MaximaleItems" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Uitleentermijn" class="control-label"></label>
                <input asp-for="Uitleentermijn" class="form-control" />
                <span asp-validation-for="Uitleentermijn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Verlengingen" class="control-label"></label>
                <input asp-for="Verlengingen" class="form-control" />
                <span asp-validation-for="Verlengingen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reserveringskosten" class="control-label"></label>
                <input asp-for="Reserveringskosten" class="form-control" />
                <span asp-validation-for="Reserveringskosten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Boetekosten" class="control-label"></label>
                <input asp-for="Boetekosten" class="form-control" />
                <span asp-validation-for="Boetekosten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Abonnementskosten" class="control-label"></label>
                <input asp-for="Abonnementskosten" class="form-control" />
                <span asp-validation-for="Abonnementskosten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="IndexAbonnement">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCLibraryApp/Views/Medewerker/EditAuthor.cshtml
@model MVCLibraryApp.Models.AuteurModel

@{
    ViewData["Title"] = "EditAuthor";
}

<h1>Edit</h1>

<h4>AuteurModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditAuthor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="IndexAuthor">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVCLibraryApp/Views/Medewerker/EditBezoeker.cshtml
@model MVCLibraryApp.ViewModels.BezoekerViewModel
@{
    ViewData["Title"] = "Edit Bezoeker";
}

<h1>Edit Bezoeker</h1>

<h4>BezoekerModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditBezoeker" method="post">
            <div asp-validation-summary="All" class="text-danger"></div> <!-- Display all model-level errors -->
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AbonnementID" class="control-label"></label>
                <select asp-for="AbonnementID" asp-items="ViewBag.Abonnementen" class="form-control"></select>
                <span asp-validation-for="AbonnementID" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="IndexBezoeker">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVCLibraryApp/Views/Medewerker/EditItem.cshtml
@{
    ViewData["Title"] = "EditItem";
}

@model MVCLibraryApp.Models.ItemModel

<h2>Edit Item</h2>

<form method="post">
    <input type="hidden" asp-for="ID" />

    <label for="Titel">Title:</label>
    <input id="Titel" asp-for="Titel" />

    <label for="AuteurID">Author ID:</label>
    <input id="AuteurID" asp-for="AuteurID" />

    <label for="Publicatiejaar">Publication Year:</label>
    <input id="Publicatiejaar" asp-for="Publicatiejaar" />

    <label for="Status">Status:</label>
    <input id="Status" asp-for="Status" />

    <label for="LocatieID">Location ID:</label>
    <input id="LocatieID" asp-for="LocatieID" />

    <button type="submit">Save</button>
</form>

MVCLibraryApp/Views/Medewerker/IndexBezoeker.cshtml
@model IEnumerable<BezoekerModel>

@{
    ViewData["Title"] = "IndexBezoeker";
}

<h2>IndexBezoeker</h2>

<p>
    <a asp-area="" asp-controller="Medewerker" asp-action="CreateBezoeker">Add a new user</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Role</th>
            <th>Email</th>
            <th>Membership status</th>
            <th>Changes</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var bezoeker in Model)
        {
            <tr>
                <td>@bezoeker.UserName</td>
                <td>
                    @foreach (var rol in ViewBag.Rol[bezoeker.Id])
                    {
                        @rol
                    }
                </td>
                <td>@bezoeker.Email</td>
                <td>@bezoeker.Abonnement.Type</td>
                <td>
                    <a asp-controller="Medewerker" asp-action="EditBezoeker" asp-route-id="@bezoeker.Id">Edit</a> |

                    <!-- DELETE Form -->
                    <form asp-controller="Medewerker" asp-action="DeleteBezoeker" asp-route-id="@bezoeker.Id" method="post" style="display: inline-block;">
                        <button type="submit">Delete</button>
                    </form>

                </td>
                <td>
                    <form asp-controller="Medewerker" asp-action="ToggleBlockUser" method="post">
                        <input type="hidden" name="id" value="@bezoeker.Id" />
                        <button type="submit">
                            @if (ViewBag.LockoutStatus[bezoeker.Id])
                            {
                                <text>Unblock</text>
                            }
                            else
                            {
                                <text>Block</text>
                            }
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>